public class Ounce {
    private double weight;
    private float weightInOunce;

    // Whenever we use final with any field it becomes required in java
    // Dart main hamaray pas required keyword hai  

    public Ounce() {
    }

    public Ounce(float weightInOunce) {
        if(weightInOunce>=0) this.weightInOunce = weightInOunce;
    }

    public Ounce(double  weight) {
        if(weight>=0) this.weight = weight * 35.274;
    }

    public double getWeight() {
        return this.weight;
    }

    public void setWeight(float weight) {
        this.weight = weight;
    }

    public float getWeightInOunce() {
        return this.weightInOunce;
    }

    public void setWeightInOunce(float weightInOunce) {
        this.weightInOunce = weightInOunce;
    }



    // generated by java Entension

    // @Override
    // public boolean equals(Object o) {
    //     if (o == this)
    //         return true;
    //     if (!(o instanceof Ounce)) {
    //         return false;
    //     }
    //     Ounce ounce = (Ounce) o;
    //     return weight == ounce.weight && weightInOunce == ounce.weightInOunce;
    // }

    // @Override
    // public int hashCode() {
    //     return Objects.hash(weight, weightInOunce);
    // }

    // @Override
    // public String toString() {
    //     return "{" +
    //             " weight='" + getWeight() + "'" +
    //             ", weightInOunce='" + getWeightInOunce() + "'" +
    //             "}";}
    
}